# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-12 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Wiadomosc', 'verbose_name_plural': 'Wiadomosci'},
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, upload_to='icons', verbose_name='Ikonka Kategorii'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nazwa Kategorii'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='Odnosnik'),
        ),
        migrations.AlterField(
            model_name='news',
            name='categories',
            field=models.ManyToManyField(to='news.Category', verbose_name='Kategorie'),
        ),
        migrations.AlterField(
            model_name='news',
            name='posted_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data dodania'),
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Odnosnik'),
        ),
        migrations.AlterField(
            model_name='news',
            name='text',
            field=models.TextField(verbose_name='Tresc'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Tytul'),
        ),
    ]
